/*
 * Supplemental Health Plan API
 * API to create or update supplemental accident indemnity health plan data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: IntegrationCenter@alight.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alight.microservice.getplan.model;

import java.util.Objects;
import java.util.Arrays;
import com.alight.microservice.getplan.model.Plan;
import com.alight.microservice.getplan.model.ThresholdReport;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * HealthPlanRequest
 */



public class HealthPlanRequest implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("sourceSystem")
  private String sourceSystem = null;

  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("plans")
  private List<Plan> plans = new ArrayList<>();

  

  public HealthPlanRequest sourceSystem(String sourceSystem) {
    this.sourceSystem = sourceSystem;
    return this;
  }

   /**
   * Get sourceSystem
   * @return sourceSystem
  **/
  @Schema(required = true, description = "")
  public String getSourceSystem() {
    return sourceSystem;
  }

  public void setSourceSystem(String sourceSystem) {
    this.sourceSystem = sourceSystem;
  }

  public HealthPlanRequest clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @Schema(required = true, description = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public HealthPlanRequest plans(List<Plan> plans) {
    this.plans = plans;
    return this;
  }

  public HealthPlanRequest addPlansItem(Plan plansItem) {
    this.plans.add(plansItem);
    return this;
  }

   /**
   * Get plans
   * @return plans
  **/
  @Schema(required = true, description = "")
  public List<Plan> getPlans() {
    return plans;
  }

  public void setPlans(List<Plan> plans) {
    this.plans = plans;
  }

  


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HealthPlanRequest healthPlanRequest = (HealthPlanRequest) o;
    return Objects.equals(this.sourceSystem, healthPlanRequest.sourceSystem) &&
        Objects.equals(this.clientId, healthPlanRequest.clientId) &&
        Objects.equals(this.plans, healthPlanRequest.plans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceSystem, clientId, plans);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HealthPlanRequest {\n");
    
    sb.append("    sourceSystem: ").append(toIndentedString(sourceSystem)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    plans: ").append(toIndentedString(plans)).append("\n");
   
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
