/*
 * Supplemental Health Plan API
 * API to create or update supplemental accident indemnity health plan data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: IntegrationCenter@alight.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alight.microservice.getplan.model;

import java.util.Objects;
import java.util.Arrays;
import com.alight.microservice.getplan.model.Service;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * Network
 */



public class Network implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("networkType")
  private String networkType = null;

  @JsonProperty("coinsurancePercent")
  private BigDecimal coinsurancePercent = null;

  @JsonProperty("copayAmount")
  private BigDecimal copayAmount = null;

  @JsonProperty("individualAnnualDeductibleAmount")
  private BigDecimal individualAnnualDeductibleAmount = null;

  @JsonProperty("singleAnnualDeductibleAmount")
  private BigDecimal singleAnnualDeductibleAmount = null;

  @JsonProperty("familyAnnualDeductibleAmount")
  private BigDecimal familyAnnualDeductibleAmount = null;

  @JsonProperty("individualOutOfPocketMaxAmount")
  private BigDecimal individualOutOfPocketMaxAmount = null;

  @JsonProperty("singleOutOfPocketMaxAmount")
  private BigDecimal singleOutOfPocketMaxAmount = null;

  @JsonProperty("familyOutOfPocketMaxAmount")
  private BigDecimal familyOutOfPocketMaxAmount = null;

  @JsonProperty("individualAnnualLimit")
  private BigDecimal individualAnnualLimit = null;

  @JsonProperty("familyAnnualLimit")
  private BigDecimal familyAnnualLimit = null;

  @JsonProperty("lifeTimeLimit")
  private BigDecimal lifeTimeLimit = null;

  @JsonProperty("subscriberWellnessBenefit")
  private BigDecimal subscriberWellnessBenefit = null;

  @JsonProperty("spouseWellnessBenefit")
  private BigDecimal spouseWellnessBenefit = null;

  @JsonProperty("childWellnessBenefit")
  private BigDecimal childWellnessBenefit = null;

  @JsonProperty("wellnessChildLimit")
  private BigDecimal wellnessChildLimit = null;

  @JsonProperty("hasPreventiveCare")
  private Boolean hasPreventiveCare = null;

  @JsonProperty("isCopayDeductible")
  private Boolean isCopayDeductible = null;

  @JsonProperty("onlyCoversEnumeratedServices")
  private Boolean onlyCoversEnumeratedServices = null;

  @JsonProperty("payOutStartingOn")
  private String payOutStartingOn = null;

  @JsonProperty("services")
  private List<Service> services = null;

  public Network networkType(String networkType) {
    this.networkType = networkType;
    return this;
  }

   /**
   * Get networkType
   * @return networkType
  **/
  @Schema(description = "")
  public String getNetworkType() {
    return networkType;
  }

  public void setNetworkType(String networkType) {
    this.networkType = networkType;
  }

  public Network coinsurancePercent(BigDecimal coinsurancePercent) {
    this.coinsurancePercent = coinsurancePercent;
    return this;
  }

   /**
   * Get coinsurancePercent
   * @return coinsurancePercent
  **/
  @Schema(description = "")
  public BigDecimal getCoinsurancePercent() {
    return coinsurancePercent;
  }

  public void setCoinsurancePercent(BigDecimal coinsurancePercent) {
    this.coinsurancePercent = coinsurancePercent;
  }

  public Network copayAmount(BigDecimal copayAmount) {
    this.copayAmount = copayAmount;
    return this;
  }

   /**
   * Get copayAmount
   * @return copayAmount
  **/
  @Schema(description = "")
  public BigDecimal getCopayAmount() {
    return copayAmount;
  }

  public void setCopayAmount(BigDecimal copayAmount) {
    this.copayAmount = copayAmount;
  }

  public Network individualAnnualDeductibleAmount(BigDecimal individualAnnualDeductibleAmount) {
    this.individualAnnualDeductibleAmount = individualAnnualDeductibleAmount;
    return this;
  }

   /**
   * Get individualAnnualDeductibleAmount
   * @return individualAnnualDeductibleAmount
  **/
  @Schema(description = "")
  public BigDecimal getIndividualAnnualDeductibleAmount() {
    return individualAnnualDeductibleAmount;
  }

  public void setIndividualAnnualDeductibleAmount(BigDecimal individualAnnualDeductibleAmount) {
    this.individualAnnualDeductibleAmount = individualAnnualDeductibleAmount;
  }

  public Network singleAnnualDeductibleAmount(BigDecimal singleAnnualDeductibleAmount) {
    this.singleAnnualDeductibleAmount = singleAnnualDeductibleAmount;
    return this;
  }

   /**
   * Get singleAnnualDeductibleAmount
   * @return singleAnnualDeductibleAmount
  **/
  @Schema(description = "")
  public BigDecimal getSingleAnnualDeductibleAmount() {
    return singleAnnualDeductibleAmount;
  }

  public void setSingleAnnualDeductibleAmount(BigDecimal singleAnnualDeductibleAmount) {
    this.singleAnnualDeductibleAmount = singleAnnualDeductibleAmount;
  }

  public Network familyAnnualDeductibleAmount(BigDecimal familyAnnualDeductibleAmount) {
    this.familyAnnualDeductibleAmount = familyAnnualDeductibleAmount;
    return this;
  }

   /**
   * Get familyAnnualDeductibleAmount
   * @return familyAnnualDeductibleAmount
  **/
  @Schema(description = "")
  public BigDecimal getFamilyAnnualDeductibleAmount() {
    return familyAnnualDeductibleAmount;
  }

  public void setFamilyAnnualDeductibleAmount(BigDecimal familyAnnualDeductibleAmount) {
    this.familyAnnualDeductibleAmount = familyAnnualDeductibleAmount;
  }

  public Network individualOutOfPocketMaxAmount(BigDecimal individualOutOfPocketMaxAmount) {
    this.individualOutOfPocketMaxAmount = individualOutOfPocketMaxAmount;
    return this;
  }

   /**
   * Get individualOutOfPocketMaxAmount
   * @return individualOutOfPocketMaxAmount
  **/
  @Schema(description = "")
  public BigDecimal getIndividualOutOfPocketMaxAmount() {
    return individualOutOfPocketMaxAmount;
  }

  public void setIndividualOutOfPocketMaxAmount(BigDecimal individualOutOfPocketMaxAmount) {
    this.individualOutOfPocketMaxAmount = individualOutOfPocketMaxAmount;
  }

  public Network singleOutOfPocketMaxAmount(BigDecimal singleOutOfPocketMaxAmount) {
    this.singleOutOfPocketMaxAmount = singleOutOfPocketMaxAmount;
    return this;
  }

   /**
   * Get singleOutOfPocketMaxAmount
   * @return singleOutOfPocketMaxAmount
  **/
  @Schema(description = "")
  public BigDecimal getSingleOutOfPocketMaxAmount() {
    return singleOutOfPocketMaxAmount;
  }

  public void setSingleOutOfPocketMaxAmount(BigDecimal singleOutOfPocketMaxAmount) {
    this.singleOutOfPocketMaxAmount = singleOutOfPocketMaxAmount;
  }

  public Network familyOutOfPocketMaxAmount(BigDecimal familyOutOfPocketMaxAmount) {
    this.familyOutOfPocketMaxAmount = familyOutOfPocketMaxAmount;
    return this;
  }

   /**
   * Get familyOutOfPocketMaxAmount
   * @return familyOutOfPocketMaxAmount
  **/
  @Schema(description = "")
  public BigDecimal getFamilyOutOfPocketMaxAmount() {
    return familyOutOfPocketMaxAmount;
  }

  public void setFamilyOutOfPocketMaxAmount(BigDecimal familyOutOfPocketMaxAmount) {
    this.familyOutOfPocketMaxAmount = familyOutOfPocketMaxAmount;
  }

  public Network individualAnnualLimit(BigDecimal individualAnnualLimit) {
    this.individualAnnualLimit = individualAnnualLimit;
    return this;
  }

   /**
   * Get individualAnnualLimit
   * @return individualAnnualLimit
  **/
  @Schema(description = "")
  public BigDecimal getIndividualAnnualLimit() {
    return individualAnnualLimit;
  }

  public void setIndividualAnnualLimit(BigDecimal individualAnnualLimit) {
    this.individualAnnualLimit = individualAnnualLimit;
  }

  public Network familyAnnualLimit(BigDecimal familyAnnualLimit) {
    this.familyAnnualLimit = familyAnnualLimit;
    return this;
  }

   /**
   * Get familyAnnualLimit
   * @return familyAnnualLimit
  **/
  @Schema(description = "")
  public BigDecimal getFamilyAnnualLimit() {
    return familyAnnualLimit;
  }

  public void setFamilyAnnualLimit(BigDecimal familyAnnualLimit) {
    this.familyAnnualLimit = familyAnnualLimit;
  }

  public Network lifeTimeLimit(BigDecimal lifeTimeLimit) {
    this.lifeTimeLimit = lifeTimeLimit;
    return this;
  }

   /**
   * Get lifeTimeLimit
   * @return lifeTimeLimit
  **/
  @Schema(description = "")
  public BigDecimal getLifeTimeLimit() {
    return lifeTimeLimit;
  }

  public void setLifeTimeLimit(BigDecimal lifeTimeLimit) {
    this.lifeTimeLimit = lifeTimeLimit;
  }

  public Network subscriberWellnessBenefit(BigDecimal subscriberWellnessBenefit) {
    this.subscriberWellnessBenefit = subscriberWellnessBenefit;
    return this;
  }

   /**
   * Get subscriberWellnessBenefit
   * @return subscriberWellnessBenefit
  **/
  @Schema(description = "")
  public BigDecimal getSubscriberWellnessBenefit() {
    return subscriberWellnessBenefit;
  }

  public void setSubscriberWellnessBenefit(BigDecimal subscriberWellnessBenefit) {
    this.subscriberWellnessBenefit = subscriberWellnessBenefit;
  }

  public Network spouseWellnessBenefit(BigDecimal spouseWellnessBenefit) {
    this.spouseWellnessBenefit = spouseWellnessBenefit;
    return this;
  }

   /**
   * Get spouseWellnessBenefit
   * @return spouseWellnessBenefit
  **/
  @Schema(description = "")
  public BigDecimal getSpouseWellnessBenefit() {
    return spouseWellnessBenefit;
  }

  public void setSpouseWellnessBenefit(BigDecimal spouseWellnessBenefit) {
    this.spouseWellnessBenefit = spouseWellnessBenefit;
  }

  public Network childWellnessBenefit(BigDecimal childWellnessBenefit) {
    this.childWellnessBenefit = childWellnessBenefit;
    return this;
  }

   /**
   * Get childWellnessBenefit
   * @return childWellnessBenefit
  **/
  @Schema(description = "")
  public BigDecimal getChildWellnessBenefit() {
    return childWellnessBenefit;
  }

  public void setChildWellnessBenefit(BigDecimal childWellnessBenefit) {
    this.childWellnessBenefit = childWellnessBenefit;
  }

  public Network wellnessChildLimit(BigDecimal wellnessChildLimit) {
    this.wellnessChildLimit = wellnessChildLimit;
    return this;
  }

   /**
   * Get wellnessChildLimit
   * @return wellnessChildLimit
  **/
  @Schema(description = "")
  public BigDecimal getWellnessChildLimit() {
    return wellnessChildLimit;
  }

  public void setWellnessChildLimit(BigDecimal wellnessChildLimit) {
    this.wellnessChildLimit = wellnessChildLimit;
  }

  public Network hasPreventiveCare(Boolean hasPreventiveCare) {
    this.hasPreventiveCare = hasPreventiveCare;
    return this;
  }

   /**
   * Get hasPreventiveCare
   * @return hasPreventiveCare
  **/
  @Schema(description = "")
  public Boolean isHasPreventiveCare() {
    return hasPreventiveCare;
  }

  public void setHasPreventiveCare(Boolean hasPreventiveCare) {
    this.hasPreventiveCare = hasPreventiveCare;
  }

  public Network isCopayDeductible(Boolean isCopayDeductible) {
    this.isCopayDeductible = isCopayDeductible;
    return this;
  }

   /**
   * Get isCopayDeductible
   * @return isCopayDeductible
  **/
  @Schema(description = "")
  public Boolean isIsCopayDeductible() {
    return isCopayDeductible;
  }

  public void setIsCopayDeductible(Boolean isCopayDeductible) {
    this.isCopayDeductible = isCopayDeductible;
  }

  public Network onlyCoversEnumeratedServices(Boolean onlyCoversEnumeratedServices) {
    this.onlyCoversEnumeratedServices = onlyCoversEnumeratedServices;
    return this;
  }

   /**
   * Get onlyCoversEnumeratedServices
   * @return onlyCoversEnumeratedServices
  **/
  @Schema(description = "")
  public Boolean isOnlyCoversEnumeratedServices() {
    return onlyCoversEnumeratedServices;
  }

  public void setOnlyCoversEnumeratedServices(Boolean onlyCoversEnumeratedServices) {
    this.onlyCoversEnumeratedServices = onlyCoversEnumeratedServices;
  }

  public Network payOutStartingOn(String payOutStartingOn) {
    this.payOutStartingOn = payOutStartingOn;
    return this;
  }

   /**
   * Get payOutStartingOn
   * @return payOutStartingOn
  **/
  @Schema(description = "")
  public String getPayOutStartingOn() {
    return payOutStartingOn;
  }

  public void setPayOutStartingOn(String payOutStartingOn) {
    this.payOutStartingOn = payOutStartingOn;
  }

  public Network services(List<Service> services) {
    this.services = services;
    return this;
  }

  public Network addServicesItem(Service servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  @Schema(description = "")
  public List<Service> getServices() {
    return services;
  }

  public void setServices(List<Service> services) {
    this.services = services;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Network network = (Network) o;
    return Objects.equals(this.networkType, network.networkType) &&
        Objects.equals(this.coinsurancePercent, network.coinsurancePercent) &&
        Objects.equals(this.copayAmount, network.copayAmount) &&
        Objects.equals(this.individualAnnualDeductibleAmount, network.individualAnnualDeductibleAmount) &&
        Objects.equals(this.singleAnnualDeductibleAmount, network.singleAnnualDeductibleAmount) &&
        Objects.equals(this.familyAnnualDeductibleAmount, network.familyAnnualDeductibleAmount) &&
        Objects.equals(this.individualOutOfPocketMaxAmount, network.individualOutOfPocketMaxAmount) &&
        Objects.equals(this.singleOutOfPocketMaxAmount, network.singleOutOfPocketMaxAmount) &&
        Objects.equals(this.familyOutOfPocketMaxAmount, network.familyOutOfPocketMaxAmount) &&
        Objects.equals(this.individualAnnualLimit, network.individualAnnualLimit) &&
        Objects.equals(this.familyAnnualLimit, network.familyAnnualLimit) &&
        Objects.equals(this.lifeTimeLimit, network.lifeTimeLimit) &&
        Objects.equals(this.subscriberWellnessBenefit, network.subscriberWellnessBenefit) &&
        Objects.equals(this.spouseWellnessBenefit, network.spouseWellnessBenefit) &&
        Objects.equals(this.childWellnessBenefit, network.childWellnessBenefit) &&
        Objects.equals(this.wellnessChildLimit, network.wellnessChildLimit) &&
        Objects.equals(this.hasPreventiveCare, network.hasPreventiveCare) &&
        Objects.equals(this.isCopayDeductible, network.isCopayDeductible) &&
        Objects.equals(this.onlyCoversEnumeratedServices, network.onlyCoversEnumeratedServices) &&
        Objects.equals(this.payOutStartingOn, network.payOutStartingOn) &&
        Objects.equals(this.services, network.services);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkType, coinsurancePercent, copayAmount, individualAnnualDeductibleAmount, singleAnnualDeductibleAmount, familyAnnualDeductibleAmount, individualOutOfPocketMaxAmount, singleOutOfPocketMaxAmount, familyOutOfPocketMaxAmount, individualAnnualLimit, familyAnnualLimit, lifeTimeLimit, subscriberWellnessBenefit, spouseWellnessBenefit, childWellnessBenefit, wellnessChildLimit, hasPreventiveCare, isCopayDeductible, onlyCoversEnumeratedServices, payOutStartingOn, services);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Network {\n");
    
    sb.append("    networkType: ").append(toIndentedString(networkType)).append("\n");
    sb.append("    coinsurancePercent: ").append(toIndentedString(coinsurancePercent)).append("\n");
    sb.append("    copayAmount: ").append(toIndentedString(copayAmount)).append("\n");
    sb.append("    individualAnnualDeductibleAmount: ").append(toIndentedString(individualAnnualDeductibleAmount)).append("\n");
    sb.append("    singleAnnualDeductibleAmount: ").append(toIndentedString(singleAnnualDeductibleAmount)).append("\n");
    sb.append("    familyAnnualDeductibleAmount: ").append(toIndentedString(familyAnnualDeductibleAmount)).append("\n");
    sb.append("    individualOutOfPocketMaxAmount: ").append(toIndentedString(individualOutOfPocketMaxAmount)).append("\n");
    sb.append("    singleOutOfPocketMaxAmount: ").append(toIndentedString(singleOutOfPocketMaxAmount)).append("\n");
    sb.append("    familyOutOfPocketMaxAmount: ").append(toIndentedString(familyOutOfPocketMaxAmount)).append("\n");
    sb.append("    individualAnnualLimit: ").append(toIndentedString(individualAnnualLimit)).append("\n");
    sb.append("    familyAnnualLimit: ").append(toIndentedString(familyAnnualLimit)).append("\n");
    sb.append("    lifeTimeLimit: ").append(toIndentedString(lifeTimeLimit)).append("\n");
    sb.append("    subscriberWellnessBenefit: ").append(toIndentedString(subscriberWellnessBenefit)).append("\n");
    sb.append("    spouseWellnessBenefit: ").append(toIndentedString(spouseWellnessBenefit)).append("\n");
    sb.append("    childWellnessBenefit: ").append(toIndentedString(childWellnessBenefit)).append("\n");
    sb.append("    wellnessChildLimit: ").append(toIndentedString(wellnessChildLimit)).append("\n");
    sb.append("    hasPreventiveCare: ").append(toIndentedString(hasPreventiveCare)).append("\n");
    sb.append("    isCopayDeductible: ").append(toIndentedString(isCopayDeductible)).append("\n");
    sb.append("    onlyCoversEnumeratedServices: ").append(toIndentedString(onlyCoversEnumeratedServices)).append("\n");
    sb.append("    payOutStartingOn: ").append(toIndentedString(payOutStartingOn)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
