/*
 * Supplemental Health Plan API
 * API to create or update supplemental accident indemnity health plan data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: IntegrationCenter@alight.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alight.microservice.getplan.model;

import java.util.Objects;
import java.util.Arrays;
import com.alight.microservice.getplan.model.PlanOption;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * Plan
 */



public class Plan implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("planId")
  private String planId = null;

  @JsonProperty("planType")
  private String planType = null;

  @JsonProperty("effectiveBeginDate")
  private String effectiveBeginDate = null;

  @JsonProperty("effectiveEndDate")
  private String effectiveEndDate = null;

  @JsonProperty("options")
  private List<PlanOption> options = null;
  @JsonProperty("thresholdReportData")
  private List<ThresholdReport> thresholdReportData = null;
  
  public Plan planId(String planId) {
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @Schema(required = true, description = "")
  public String getPlanId() {
    return planId;
  }

  public void setPlanId(String planId) {
    this.planId = planId;
  }

  public Plan planType(String planType) {
    this.planType = planType;
    return this;
  }

   /**
   * Get planType
   * @return planType
  **/
  @Schema(required = true, description = "")
  public String getPlanType() {
    return planType;
  }

  public void setPlanType(String planType) {
    this.planType = planType;
  }

  public Plan effectiveBeginDate(String effectiveBeginDate) {
    this.effectiveBeginDate = effectiveBeginDate;
    return this;
  }

   /**
   * Get effectiveBeginDate
   * @return effectiveBeginDate
  **/
  @Schema(required = true, description = "")
  public String getEffectiveBeginDate() {
    return effectiveBeginDate;
  }

  public void setEffectiveBeginDate(String effectiveBeginDate) {
    this.effectiveBeginDate = effectiveBeginDate;
  }

  public Plan effectiveEndDate(String effectiveEndDate) {
    this.effectiveEndDate = effectiveEndDate;
    return this;
  }

   /**
   * Get effectiveEndDate
   * @return effectiveEndDate
  **/
  @Schema(required = true, description = "")
  public String getEffectiveEndDate() {
    return effectiveEndDate;
  }

  public void setEffectiveEndDate(String effectiveEndDate) {
    this.effectiveEndDate = effectiveEndDate;
  }

  public Plan options(List<PlanOption> options) {
    this.options = options;
    return this;
  }

  public Plan addOptionsItem(PlanOption optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }
    this.options.add(optionsItem);
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @Schema(description = "")
  public List<PlanOption> getOptions() {
    return options;
  }

  public void setOptions(List<PlanOption> options) {
    this.options = options;
  }
  
  public Plan thresholdReportData(List<ThresholdReport> thresholdReportData) {
	    this.thresholdReportData = thresholdReportData;
	    return this;
	  }

	  public Plan addThresholdReportDataItem(ThresholdReport thresholdReportDataItem) {
	    if (this.thresholdReportData == null) {
	      this.thresholdReportData = new ArrayList<>();
	    }
	    this.thresholdReportData.add(thresholdReportDataItem);
	    return this;
	  }

	   /**
	   * Get thresholdReportData
	   * @return thresholdReportData
	  **/
	  @Schema(description = "")
	  public List<ThresholdReport> getThresholdReportData() {
	    return thresholdReportData;
	  }

	  public void setThresholdReportData(List<ThresholdReport> thresholdReportData) {
	    this.thresholdReportData = thresholdReportData;
	  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plan plan = (Plan) o;
    return Objects.equals(this.planId, plan.planId) &&
        Objects.equals(this.planType, plan.planType) &&
        Objects.equals(this.effectiveBeginDate, plan.effectiveBeginDate) &&
        Objects.equals(this.effectiveEndDate, plan.effectiveEndDate) &&
        Objects.equals(this.options, plan.options) &&
        Objects.equals(this.thresholdReportData, plan.thresholdReportData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(planId, planType, effectiveBeginDate, effectiveEndDate, options, thresholdReportData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plan {\n");
    
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    planType: ").append(toIndentedString(planType)).append("\n");
    sb.append("    effectiveBeginDate: ").append(toIndentedString(effectiveBeginDate)).append("\n");
    sb.append("    effectiveEndDate: ").append(toIndentedString(effectiveEndDate)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    thresholdReportData: ").append(toIndentedString(thresholdReportData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
