/*
 * Supplemental Health Plan API
 * API to create or update supplemental accident indemnity health plan data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: IntegrationCenter@alight.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alight.microservice.getplan.model;

import java.util.Objects;
import java.util.Arrays;
import com.alight.microservice.getplan.model.Network;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * PlanOption
 */



public class PlanOption implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("optionId")
  private String optionId = null;

  @JsonProperty("optionType")
  private String optionType = null;

  @JsonProperty("compositePlanDesignId")
  private String compositePlanDesignId = null;

  @JsonProperty("coverageId")
  private String coverageId = null;

  @JsonProperty("hcCarrierPrcsID")
  private String hcCarrierPrcsID = null;

  @JsonProperty("networks")
  private List<Network> networks = null;

  public PlanOption optionId(String optionId) {
    this.optionId = optionId;
    return this;
  }

   /**
   * Get optionId
   * @return optionId
  **/
  @Schema(description = "")
  public String getOptionId() {
    return optionId;
  }

  public void setOptionId(String optionId) {
    this.optionId = optionId;
  }

  public PlanOption optionType(String optionType) {
    this.optionType = optionType;
    return this;
  }

   /**
   * Get optionType
   * @return optionType
  **/
  @Schema(description = "")
  public String getOptionType() {
    return optionType;
  }

  public void setOptionType(String optionType) {
    this.optionType = optionType;
  }

  public PlanOption compositePlanDesignId(String compositePlanDesignId) {
    this.compositePlanDesignId = compositePlanDesignId;
    return this;
  }

   /**
   * Get compositePlanDesignId
   * @return compositePlanDesignId
  **/
  @Schema(description = "")
  public String getCompositePlanDesignId() {
    return compositePlanDesignId;
  }

  public void setCompositePlanDesignId(String compositePlanDesignId) {
    this.compositePlanDesignId = compositePlanDesignId;
  }

  public PlanOption coverageId(String coverageId) {
    this.coverageId = coverageId;
    return this;
  }

   /**
   * Get coverageId
   * @return coverageId
  **/
  @Schema(description = "")
  public String getCoverageId() {
    return coverageId;
  }

  public void setCoverageId(String coverageId) {
    this.coverageId = coverageId;
  }

  public PlanOption hcCarrierPrcsID(String hcCarrierPrcsID) {
    this.hcCarrierPrcsID = hcCarrierPrcsID;
    return this;
  }

   /**
   * Get hcCarrierPrcsID
   * @return hcCarrierPrcsID
  **/
  @Schema(description = "")
  public String getHcCarrierPrcsID() {
    return hcCarrierPrcsID;
  }

  public void setHcCarrierPrcsID(String hcCarrierPrcsID) {
    this.hcCarrierPrcsID = hcCarrierPrcsID;
  }

  public PlanOption networks(List<Network> networks) {
    this.networks = networks;
    return this;
  }

  public PlanOption addNetworksItem(Network networksItem) {
    if (this.networks == null) {
      this.networks = new ArrayList<>();
    }
    this.networks.add(networksItem);
    return this;
  }

   /**
   * Get networks
   * @return networks
  **/
  @Schema(description = "")
  public List<Network> getNetworks() {
    return networks;
  }

  public void setNetworks(List<Network> networks) {
    this.networks = networks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanOption planOption = (PlanOption) o;
    return Objects.equals(this.optionId, planOption.optionId) &&
        Objects.equals(this.optionType, planOption.optionType) &&
        Objects.equals(this.compositePlanDesignId, planOption.compositePlanDesignId) &&
        Objects.equals(this.coverageId, planOption.coverageId) &&
        Objects.equals(this.hcCarrierPrcsID, planOption.hcCarrierPrcsID) &&
        Objects.equals(this.networks, planOption.networks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optionId, optionType, compositePlanDesignId, coverageId, hcCarrierPrcsID, networks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanOption {\n");
    
    sb.append("    optionId: ").append(toIndentedString(optionId)).append("\n");
    sb.append("    optionType: ").append(toIndentedString(optionType)).append("\n");
    sb.append("    compositePlanDesignId: ").append(toIndentedString(compositePlanDesignId)).append("\n");
    sb.append("    coverageId: ").append(toIndentedString(coverageId)).append("\n");
    sb.append("    hcCarrierPrcsID: ").append(toIndentedString(hcCarrierPrcsID)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
