/*
 * Supplemental Health Plan API
 * API to create or update supplemental accident indemnity health plan data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: IntegrationCenter@alight.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alight.microservice.getplan.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.io.Serializable;
/**
 * ServiceAttribute
 */



public class ServiceAttribute implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("attributeName")
  private String attributeName = null;

  @JsonProperty("attributeValue")
  private BigDecimal attributeValue = null;

  @JsonProperty("attributeType")
  private String attributeType = null;

  public ServiceAttribute attributeName(String attributeName) {
    this.attributeName = attributeName;
    return this;
  }

   /**
   * Get attributeName
   * @return attributeName
  **/
  @Schema(required = true, description = "")
  public String getAttributeName() {
    return attributeName;
  }

  public void setAttributeName(String attributeName) {
    this.attributeName = attributeName;
  }

  public ServiceAttribute attributeValue(BigDecimal attributeValue) {
    this.attributeValue = attributeValue;
    return this;
  }

   /**
   * Get attributeValue
   * @return attributeValue
  **/
  @Schema(required = true, description = "")
  public BigDecimal getAttributeValue() {
    return attributeValue;
  }

  public void setAttributeValue(BigDecimal attributeValue) {
    this.attributeValue = attributeValue;
  }

  public ServiceAttribute attributeType(String attributeType) {
    this.attributeType = attributeType;
    return this;
  }

   /**
   * Get attributeType
   * @return attributeType
  **/
  @Schema(required = true, description = "")
  public String getAttributeType() {
    return attributeType;
  }

  public void setAttributeType(String attributeType) {
    this.attributeType = attributeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceAttribute serviceAttribute = (ServiceAttribute) o;
    return Objects.equals(this.attributeName, serviceAttribute.attributeName) &&
        Objects.equals(this.attributeValue, serviceAttribute.attributeValue) &&
        Objects.equals(this.attributeType, serviceAttribute.attributeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeName, attributeValue, attributeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceAttribute {\n");
    
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    attributeValue: ").append(toIndentedString(attributeValue)).append("\n");
    sb.append("    attributeType: ").append(toIndentedString(attributeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
