/*
 * Supplemental Health Plan API
 * API to create or update supplemental accident indemnity health plan data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: IntegrationCenter@alight.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alight.microservice.getplan.model;

import java.util.Objects;
import java.util.Arrays;
import com.alight.microservice.getplan.model.ServiceAttribute;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
/**
 * Service
 */



public class Service implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("serviceType")
  private String serviceType = null;

  @JsonProperty("dataElementId")
  private String dataElementId = null;

  @JsonProperty("serviceAttributes")
  private List<ServiceAttribute> serviceAttributes = new ArrayList<>();

  public Service serviceType(String serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * Get serviceType
   * @return serviceType
  **/
  @Schema(required = true, description = "")
  public String getServiceType() {
    return serviceType;
  }

  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }

  public Service dataElementId(String dataElementId) {
    this.dataElementId = dataElementId;
    return this;
  }

   /**
   * Get dataElementId
   * @return dataElementId
  **/
  @Schema(description = "")
  public String getDataElementId() {
    return dataElementId;
  }

  public void setDataElementId(String dataElementId) {
    this.dataElementId = dataElementId;
  }

  public Service serviceAttributes(List<ServiceAttribute> serviceAttributes) {
    this.serviceAttributes = serviceAttributes;
    return this;
  }

  public Service addServiceAttributesItem(ServiceAttribute serviceAttributesItem) {
    this.serviceAttributes.add(serviceAttributesItem);
    return this;
  }

   /**
   * Get serviceAttributes
   * @return serviceAttributes
  **/
  @Schema(required = true, description = "")
  public List<ServiceAttribute> getServiceAttributes() {
    return serviceAttributes;
  }

  public void setServiceAttributes(List<ServiceAttribute> serviceAttributes) {
    this.serviceAttributes = serviceAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.serviceType, service.serviceType) &&
        Objects.equals(this.dataElementId, service.dataElementId) &&
        Objects.equals(this.serviceAttributes, service.serviceAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceType, dataElementId, serviceAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    dataElementId: ").append(toIndentedString(dataElementId)).append("\n");
    sb.append("    serviceAttributes: ").append(toIndentedString(serviceAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
