/*
 * Supplemental Health Plan API
 * API to create or update supplemental accident indemnity health plan data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: IntegrationCenter@alight.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alight.microservice.getplan.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.io.Serializable;
/**
 * ThresholdReport
 */



public class ThresholdReport implements Serializable{
  private static final long serialVersionUID = 1L;
  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("dataElementId")
  private String dataElementId = null;

  @JsonProperty("dataElementName")
  private String dataElementName = null;

  @JsonProperty("reportingEndDate")
  private String reportingEndDate = null;

  @JsonProperty("pattern")
  private String pattern = null;

  @JsonProperty("confidenceScore")
  private BigDecimal confidenceScore = null;

  @JsonProperty("result")
  private String result = null;

  public ThresholdReport clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @Schema(description = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ThresholdReport dataElementId(String dataElementId) {
    this.dataElementId = dataElementId;
    return this;
  }

   /**
   * Get dataElementId
   * @return dataElementId
  **/
  @Schema(description = "")
  public String getDataElementId() {
    return dataElementId;
  }

  public void setDataElementId(String dataElementId) {
    this.dataElementId = dataElementId;
  }

  public ThresholdReport dataElementName(String dataElementName) {
    this.dataElementName = dataElementName;
    return this;
  }

   /**
   * Get dataElementName
   * @return dataElementName
  **/
  @Schema(description = "")
  public String getDataElementName() {
    return dataElementName;
  }

  public void setDataElementName(String dataElementName) {
    this.dataElementName = dataElementName;
  }

  public ThresholdReport reportingEndDate(String reportingEndDate) {
    this.reportingEndDate = reportingEndDate;
    return this;
  }

   /**
   * Get reportingEndDate
   * @return reportingEndDate
  **/
  @Schema(description = "")
  public String getReportingEndDate() {
    return reportingEndDate;
  }

  public void setReportingEndDate(String reportingEndDate) {
    this.reportingEndDate = reportingEndDate;
  }

  public ThresholdReport pattern(String pattern) {
    this.pattern = pattern;
    return this;
  }

   /**
   * Get pattern
   * @return pattern
  **/
  @Schema(description = "")
  public String getPattern() {
    return pattern;
  }

  public void setPattern(String pattern) {
    this.pattern = pattern;
  }

  public ThresholdReport confidenceScore(BigDecimal confidenceScore) {
    this.confidenceScore = confidenceScore;
    return this;
  }

   /**
   * Get confidenceScore
   * @return confidenceScore
  **/
  @Schema(description = "")
  public BigDecimal getConfidenceScore() {
    return confidenceScore;
  }

  public void setConfidenceScore(BigDecimal confidenceScore) {
    this.confidenceScore = confidenceScore;
  }

  public ThresholdReport result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @Schema(description = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThresholdReport thresholdReport = (ThresholdReport) o;
    return Objects.equals(this.clientId, thresholdReport.clientId) &&
        Objects.equals(this.dataElementId, thresholdReport.dataElementId) &&
        Objects.equals(this.dataElementName, thresholdReport.dataElementName) &&
        Objects.equals(this.reportingEndDate, thresholdReport.reportingEndDate) &&
        Objects.equals(this.pattern, thresholdReport.pattern) &&
        Objects.equals(this.confidenceScore, thresholdReport.confidenceScore) &&
        Objects.equals(this.result, thresholdReport.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, dataElementId, dataElementName, reportingEndDate, pattern, confidenceScore, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThresholdReport {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    dataElementId: ").append(toIndentedString(dataElementId)).append("\n");
    sb.append("    dataElementName: ").append(toIndentedString(dataElementName)).append("\n");
    sb.append("    reportingEndDate: ").append(toIndentedString(reportingEndDate)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    confidenceScore: ").append(toIndentedString(confidenceScore)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
